spring:
  application:
    name: redisinterface
  data:
    redis:
      host: redis-10157.c282.east-us-mz.azure.cloud.redislabs.com
      port: 10157
      password: KDA29okWCuQJhypSLt13WUKlLCuvt1Jm
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
